puts "<header>"
puts "      <h1><a href='/'>Eureka</a></h1>"
puts "    </header>"
puts "    <nav>"
puts "      <ul>"
puts "        <li><a href='/'>Home</a></li>"
puts "        <li><a href='/about'>About</a></li>"
puts "      </ul>"
puts "    </nav>"