puts "<meta http-equiv='Content-Type' content='text/html;charset=utf-8' />"
puts "    <link rel='stylesheet' type='text/css' media='all' href='stylesheets/reset.css' />"
puts "    <link rel='stylesheet' type='text/css' media='all' href='stylesheets/style.css' />"
puts "    <!--[if IE]>"
puts "      <script src='http://html5shiv.googlecode.com/svn/trunk/html5.js'></script>"
puts "    <![endif]-->"